language: csharp
sudo: false
solution: Mond.sln
mono: none
dotnet: 2.1.101
dist: trusty
install:
  - dotnet restore
  - dotnet build Mond.Repl -f netcoreapp2.0
script:
  - dotnet run -p ./Mond.Tests/Mond.Tests.csproj -c Release
