language: csharp
sudo: false
solution: Mond.sln
mono: none
dotnet: 5.0.102
dist: xenial
install:
  - dotnet restore
  - dotnet build Mond.Repl -f net5.0 --no-restore
script:
  - dotnet run -p ./Mond.Tests/Mond.Tests.csproj -c Release
