language: csharp
sudo: false
solution: Mond.sln
mono: none
dotnet: 3.1.201
dist: xenial
install:
  - dotnet restore
  - dotnet build Mond.Repl -f netcoreapp3.1
script:
  - dotnet run -p ./Mond.Tests/Mond.Tests.csproj -c Release
