language: csharp
sudo: false
solution: Mond.sln
mono: none
dotnet: 6.0.101
dist: xenial
install:
  - dotnet restore
  - dotnet build Mond.Repl -f net6.0 --no-restore
script:
  - dotnet run -p ./Mond.Tests/Mond.Tests.csproj -c Release
