language: csharp
sudo: false
solution: Mond.sln
mono: none
dotnet: 1.0.1
dist: trusty
install:
  - dotnet restore
  - dotnet build Mond.Repl -f netcoreapp1.1
script:
  - dotnet run -p ./Mond.Tests/Mond.Tests.csproj -c Release
