name: Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        name: NuGet_packages
        path: '**/*.nupkg'
        if-no-files-found: error
        retention-days: 30
        overwrite: true
        compression-level: 0
